
import { useState } from "react";
import { toast } from "sonner";
import { employeeService } from "@/services/employee/employee.service";
import { useEmailValidation } from "./form/useEmailValidation";
import { useFormValidation } from "./form/useFormValidation";
import { useFormState } from "./form/useFormState";
import { PersonalDetailsData } from "@/components/employee/types";
import { EmployeeData } from "@/services/types/employee.types";

export const useEmployeeForm = () => {
  const [isFormCompleted, setIsFormCompleted] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const {
    activeTab,
    formProgress,
    formData,
    updateSectionProgress,
    updateFormData,
    handleTabChange,
    setActiveTab
  } = useFormState();

  const { isCheckingEmail, emailError, setEmailError } = useEmailValidation(formData.personal?.email);

  const handleSaveAndNext = async () => {
    const form = document.getElementById("personalDetailsForm") as HTMLFormElement;
    
    if (activeTab === "personal" && form) {
      setIsSubmitting(true);
      try {
        // Trigger form submission and wait for validation
        await new Promise<void>((resolve) => {
          form.addEventListener('submit', () => resolve(), { once: true });
          form.requestSubmit();
        });

        // If form submission was successful (validation passed), proceed
        const nextTab = "education";
        setActiveTab(nextTab);
      } catch (error) {
        console.error('Form validation error:', error);
      } finally {
        setIsSubmitting(false);
      }
      return;
    }

    // Handle other tabs
    const tabOrder = ["personal", "education", "bank"];
    const currentIndex = tabOrder.indexOf(activeTab);
    
    if (currentIndex < tabOrder.length - 1) {
      setActiveTab(tabOrder[currentIndex + 1]);
    } else if (currentIndex === tabOrder.length - 1) {
      // This is the final tab, submit everything
      setIsSubmitting(true);
      try {
        const employeeData: EmployeeData = {
          id: '', // Will be generated by the server
          employeeId: formData.personal!.employeeId,
          personal: formData.personal!,
          education: formData.education,
          experience: formData.experience || [],
          bank: formData.bank!,
          department: formData.personal?.department || null,
          position: formData.personal?.position || null,
          employmentStatus: 'active',
          documents: formData.personal?.documents || []
        };

        await employeeService.createEmployee(employeeData);
        toast.success("Employee information saved successfully!");
        setIsFormCompleted(true);
        window.location.reload();
      } catch (error: any) {
        console.error('Error saving employee data:', error);
        if (error.message && (error.message.includes('Employee ID') || error.message.includes('Email'))) {
          toast.error(error.message);
        } else {
          toast.error("Failed to save employee information. Please try again.");
        }
      } finally {
        setIsSubmitting(false);
      }
    }
  };

  return {
    activeTab,
    formProgress,
    formData,
    isFormCompleted,
    isSubmitting,
    isCheckingEmail,
    emailError,
    updateSectionProgress,
    updateFormData,
    handleTabChange,
    handleSaveAndNext,
  };
};
