// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjofefcmhtvrlhfwzvgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqb2ZlZmNtaHR2cmxoZnd6dmdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzMzY5OTUsImV4cCI6MjA1NDkxMjk5NX0.awgF0Hc8kGIOvTmA03t_dwir87vF3Fnkq5l5G_d6Zjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);